
# Settings

# Title of your site
title: Simplog
description: > # this means to ignore newlines until "baseurl:"
  Write the description of your website.


# the subpath of your site
# baseurl: "" # default
baseurl: "/simplog"


# Contact
email: "simplog@simplog.com" # for contact form


# Footer : scoial information
# If you don't have, just let it blank.
facebook: "facebook_link" # default: facebook: ""
instagram: "instagram_link" # default: instagram: ""
twitter: "twitter_link" # default: twitter: ""
github: "github_link" # default: github: ""


# Build settings : don't touch
markdown: kramdown
