
# Settings

# title and description of your site
title: Simplog
description: > # this means to ignore newlines until "baseurl:"
  Write the description of your website.


# the subpath of your site
# baseurl: ""          default
# baseurl: "/subpath"   subpath
baseurl: "/simplog"


# site url
# url: "http://domain.com"


# contact
# email: "example@domain.com"
email: "simplog@simplog.com"


# footer
# social informaiton
facebook: "#"
instagram: "#"
twitter: "#"
github: "#"


# Build settings : don't touch
markdown: kramdown
